version: "3.7"

services:
  sonarqube:
    image: sonarqube:8.5.1-community
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - 9000:9000
    environment:
      SONAR_ES_BOOTSTRAP_CHECKS_DISABLE: "true"
      SONAR_JDBC_URL: jdbc:postgresql://db:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    volumes:
      - ./volumes/sonarqube/conf:/opt/sonarqube/conf
      - ./volumes/sonarqube/data:/opt/sonarqube/data
      - ./volumes/sonarqube/logs:/opt/sonarqube/logs
      - ./volumes/sonarqube/extensions:/opt/sonarqube/extensions

  db:
    image: postgres:13.1-alpine
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
    volumes:
      - ./volumes/db:/var/lib/postgresql
      - ./volumes/db/data:/var/lib/postgresql/data
