version: '3'

services:
  db:
    image: mysql
    restart: unless-stopped
    ports:
      - 3306:3306
    volumes:
      - ./volumes/database:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: $DB_ROOT_PASSWORD
      MYSQL_DATABASE: $DB_DATABASE
      MYSQL_USER: $DB_USERNAME
      MYSQL_PASSWORD: $DB_PASSWORD


